server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    jdbc-url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/social_network}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  slave-datasource:
    jdbc-url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/social_network}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  sql:
    init:
      mode: ${INIT_MODE:always}

generate-users:
  false
